version: '3.8'
services:
  web:
    build: .
    container_name: jenkins_app
    ports:
      - '4000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:


