version: '3.8'

services:
  web:
    build:
      context: .
      args:
        MONGODB_URI: ${MONGODB_URI}
        EMAIL_USER: ${EMAIL_USER}
        EMAIL_PASS: ${EMAIL_PASS}
        JWT_SECRET: ${JWT_SECRET}
        CRYPTO_KEY: ${CRYPTO_KEY}
        NEXT_PUBLIC_CRYPTO_KEY: ${NEXT_PUBLIC_CRYPTO_KEY}
    container_name: jenkins_app
    ports:
      - '4000:3000'
    env_file:
      - .env.local
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
